[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "https://insightly-5iyw.onrender.com/sitemap.xml"
  status = 200
  force = true
  headers = {X-Debug = "Netlify-Redirect", Access-Control-Allow-Origin = "*", Content-Type = "application/xml"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200